packages:
  - backend
  - frontend/*
  - packages/*

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    '@types/react': ^18.3.12
    '@types/react-dom': ^18.3.1

  react19:
    react: 19.0.0-rc-66855b96-20241106
    react-dom: 19.0.0-rc-66855b96-20241106
    '@types/react': npm:types-react@rc
    '@types/react-dom': npm:types-react-dom@rc

  tailwindcss:
    autoprefixer: latest
    clsx: latest
    fluid-tailwind: latest
    postcss: latest
    tailwindcss: latest
    tailwindcss-animate: latest
    tailwind-merge: latest
