packages:
  - backend/*
  - frontend/*
  - packages/*

catalog:
  lucide-react: ^0.451.0
  tailwindcss: ^3.4.13
  eslint: ^8.57.1
  biome: ^1.9.4
  typescript: ^5.6.3
  "@types/node": ^20
  "@types/eslint": ^8

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.1
    "@types/react-dom": ^18.3.1