packages:
  - backend/*
  - frontend/*
  - packages/*

catalog:
  lucide-react: ^0.451.0
  tailwindcss: ^3.4.14
  eslint: ^8.57.1
  typescript: ^5
  "@biomejs/biome": ^1.9.4
  "@types/node": ^20
  "@types/eslint": ^8

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1
  
  react19:
    "react": "19.0.0-rc-69d4b800-20241021"
    "react-dom": "19.0.0-rc-69d4b800-20241021"
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1